sudo: false

language: ruby

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec jekyll build
  - bundle exec jekyll build-ebook --kindle

deploy:
  - provider: pages
    github-token: # TODO: Run `travis encrypt GITHUB_TOKEN`
    skip-cleanup: true
    local-dir: _site
    target_branch: gh-pages
    on:
      branch: master
  - provider: releases
    api_key: # TODO: Run `travis encrypt GITHUB_TOKEN`
    skip_cleanup: true
    file_glob: true
    file: _ebook/*
    on:
      tags: true
